// AUTO-GENERATED by scripts/buildPalette.ts. Do not edit by hand.
// Source: shared/palette.ts (OKLCH). Pre-resolved to sRGB hex for React Native.

import type { SwatchId } from '../../../shared/palette';
export type { SwatchId } from '../../../shared/palette';

export interface ResolvedSwatch {
  id: SwatchId;
  name: string;
  hue: number;
  neutral: boolean;
  dot: string;
  dotDark: string;
  bg: string;
  bgDark: string;
  surface: string;
  surfaceDark: string;
  border: string;
  borderDark: string;
  text: string;
  textDark: string;
}

export const PALETTE: ResolvedSwatch[] = [
  {
    "id": "slate",
    "name": "Slate",
    "hue": 250,
    "neutral": true,
    "dot": "#9ea6ae",
    "dotDark": "#b0b8c1",
    "bg": "#ecf1f5",
    "bgDark": "#2e3339",
    "surface": "#f6f9fb",
    "surfaceDark": "#242729",
    "border": "#86909b",
    "borderDark": "#96a0a9",
    "text": "#2b343d",
    "textDark": "#e0e5eb"
  },
  {
    "id": "red",
    "name": "Red",
    "hue": 25,
    "neutral": false,
    "dot": "#d78e88",
    "dotDark": "#eca19a",
    "bg": "#ffe5e1",
    "bgDark": "#522220",
    "surface": "#fff3f0",
    "surfaceDark": "#361f1d",
    "border": "#ce7069",
    "borderDark": "#da837c",
    "text": "#492826",
    "textDark": "#fedbd7"
  },
  {
    "id": "orange",
    "name": "Orange",
    "hue": 55,
    "neutral": false,
    "dot": "#d1966d",
    "dotDark": "#e5a880",
    "bg": "#ffe9d4",
    "bgDark": "#4e2707",
    "surface": "#fff5e9",
    "surfaceDark": "#342215",
    "border": "#c77a41",
    "borderDark": "#d28c5a",
    "text": "#462c19",
    "textDark": "#fbdecc"
  },
  {
    "id": "amber",
    "name": "Amber",
    "hue": 85,
    "neutral": false,
    "dot": "#bfa060",
    "dotDark": "#d2b373",
    "bg": "#feefcf",
    "bgDark": "#432f00",
    "surface": "#fff8e6",
    "surfaceDark": "#2e2511",
    "border": "#b18827",
    "borderDark": "#bd9948",
    "text": "#3f3112",
    "textDark": "#f1e3c7"
  },
  {
    "id": "lime",
    "name": "Lime",
    "hue": 125,
    "neutral": false,
    "dot": "#98af70",
    "dotDark": "#aac282",
    "bg": "#e9f6d5",
    "bgDark": "#2a3909",
    "surface": "#f4fcea",
    "surfaceDark": "#222a16",
    "border": "#7e9c44",
    "borderDark": "#8faa5d",
    "text": "#2d371a",
    "textDark": "#deeacd"
  },
  {
    "id": "emerald",
    "name": "Emerald",
    "hue": 155,
    "neutral": false,
    "dot": "#75b68c",
    "dotDark": "#88c99e",
    "bg": "#d9fae3",
    "bgDark": "#093d22",
    "surface": "#ecfef1",
    "surfaceDark": "#172c1f",
    "border": "#49a46e",
    "borderDark": "#63b281",
    "text": "#1c3a27",
    "textDark": "#d1edd9"
  },
  {
    "id": "teal",
    "name": "Teal",
    "hue": 190,
    "neutral": false,
    "dot": "#58b7b1",
    "dotDark": "#6ccac4",
    "bg": "#cffaf7",
    "bgDark": "#003e3b",
    "surface": "#e7fefc",
    "surfaceDark": "#0e2c2a",
    "border": "#00a69f",
    "borderDark": "#34b4ad",
    "text": "#0a3b38",
    "textDark": "#c7eeea"
  },
  {
    "id": "sky",
    "name": "Sky",
    "hue": 230,
    "neutral": false,
    "dot": "#65afd2",
    "dotDark": "#78c2e6",
    "bg": "#d2f7ff",
    "bgDark": "#003950",
    "surface": "#e8fcff",
    "surfaceDark": "#122a35",
    "border": "#259cca",
    "borderDark": "#4babd5",
    "text": "#133747",
    "textDark": "#cbeafb"
  },
  {
    "id": "blue",
    "name": "Blue",
    "hue": 260,
    "neutral": false,
    "dot": "#84a6dd",
    "dotDark": "#96b9f1",
    "bg": "#dff1ff",
    "bgDark": "#1c3257",
    "surface": "#eff9ff",
    "surfaceDark": "#1c2738",
    "border": "#638fd8",
    "borderDark": "#769fe2",
    "text": "#24334c",
    "textDark": "#d5e6ff"
  },
  {
    "id": "indigo",
    "name": "Indigo",
    "hue": 285,
    "neutral": false,
    "dot": "#9e9ddb",
    "dotDark": "#b1b0ef",
    "bg": "#ecedff",
    "bgDark": "#302c56",
    "surface": "#f6f7ff",
    "surfaceDark": "#242437",
    "border": "#8884d5",
    "borderDark": "#9795df",
    "text": "#302f4b",
    "textDark": "#e1e1ff"
  },
  {
    "id": "violet",
    "name": "Violet",
    "hue": 310,
    "neutral": false,
    "dot": "#b695cf",
    "dotDark": "#c9a8e3",
    "bg": "#f9e8ff",
    "bgDark": "#3e274e",
    "surface": "#fef4ff",
    "surfaceDark": "#2c2134",
    "border": "#a679c6",
    "borderDark": "#b38bd1",
    "text": "#3b2b46",
    "textDark": "#eddef9"
  },
  {
    "id": "pink",
    "name": "Pink",
    "hue": 350,
    "neutral": false,
    "dot": "#d08dac",
    "dotDark": "#e4a0bf",
    "bg": "#ffe4f4",
    "bgDark": "#4d2238",
    "surface": "#fff2fb",
    "surfaceDark": "#341f29",
    "border": "#c56f99",
    "borderDark": "#d182a8",
    "text": "#462836",
    "textDark": "#fbdae8"
  }
];

export const PALETTE_BY_ID: Record<SwatchId, ResolvedSwatch> = Object.fromEntries(
  PALETTE.map((p) => [p.id, p]),
) as Record<SwatchId, ResolvedSwatch>;
