/**
 * Pre-resolve the OKLCH palette from `shared/palette.ts` to sRGB hex.
 * Run via `pnpm build:palette`. Re-run when hues change.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { converter, formatHex } from 'culori';

import { PALETTE, type Swatch } from '../../shared/palette';

const toHex = (oklchString: string): string => {
  const match = oklchString.match(/^oklch\(([\d.]+)\s+([\d.]+)\s+([\d.]+)\)$/);
  if (!match) throw new Error(`Unparseable oklch string: ${oklchString}`);
  const [, l, c, h] = match;
  const hex = formatHex(converter('rgb')({ mode: 'oklch', l: Number(l), c: Number(c), h: Number(h) }));
  if (!hex) throw new Error(`Could not convert ${oklchString}`);
  return hex;
};

type ResolvedSwatch = {
  [K in keyof Swatch]: Swatch[K] extends string
    ? K extends 'id' | 'name'
      ? Swatch[K]
      : string
    : Swatch[K];
};

const resolved: ResolvedSwatch[] = PALETTE.map((swatch) => ({
  id: swatch.id,
  name: swatch.name,
  hue: swatch.hue,
  neutral: swatch.neutral,
  dot: toHex(swatch.dot),
  dotDark: toHex(swatch.dotDark),
  bg: toHex(swatch.bg),
  bgDark: toHex(swatch.bgDark),
  surface: toHex(swatch.surface),
  surfaceDark: toHex(swatch.surfaceDark),
  border: toHex(swatch.border),
  borderDark: toHex(swatch.borderDark),
  text: toHex(swatch.text),
  textDark: toHex(swatch.textDark),
}));

const file = `// AUTO-GENERATED by scripts/buildPalette.ts. Do not edit by hand.
// Source: shared/palette.ts (OKLCH). Pre-resolved to sRGB hex for React Native.

import type { SwatchId } from '../../../shared/palette';
export type { SwatchId } from '../../../shared/palette';

export interface ResolvedSwatch {
  id: SwatchId;
  name: string;
  hue: number;
  neutral: boolean;
  dot: string;
  dotDark: string;
  bg: string;
  bgDark: string;
  surface: string;
  surfaceDark: string;
  border: string;
  borderDark: string;
  text: string;
  textDark: string;
}

export const PALETTE: ResolvedSwatch[] = ${JSON.stringify(resolved, null, 2)};

export const PALETTE_BY_ID: Record<SwatchId, ResolvedSwatch> = Object.fromEntries(
  PALETTE.map((p) => [p.id, p]),
) as Record<SwatchId, ResolvedSwatch>;
`;

const outPath = resolve(__dirname, '..', 'src', 'theme', 'palette.generated.ts');
writeFileSync(outPath, file, 'utf8');
console.log(`Wrote ${outPath} (${resolved.length} swatches)`);
